{ ... }:

{
  # Crypto modules in initrd for LUKS unlock at boot
  boot.initrd.availableKernelModules = [ "aesni_intel" "cryptd" ];

  # Security model:
  # - Device OFF: LUKS fully protects all data.
  # - Device sleeping (S2RAM) with screen locked: LUKS key is in RAM but
  #   swaylock blocks access. Cold-boot attack requires specialist hardware
  #   and access within minutes of the device sleeping.
  # Note: cryptsetup-suspend (luksSuspend/luksResume) was removed; it caused
  # hangs during the sleep path when pending I/O couldn't drain in time.
  #
  # Note: boot.initrd.luks.devices.cryptroot is generated by
  # nixos-generate-config after install (it detects the LUKS root).
  # allowDiscards can be added there manually if desired.
}
