{ ... }:

{
  # Crypto modules in initrd for LUKS unlock at boot
  boot.initrd.availableKernelModules = [ "aesni_intel" "cryptd" ];

  # Security model:
  # - Device OFF or hibernated: LUKS fully protects all data.
  # - Device sleeping (S2RAM) with screen locked: LUKS key is in RAM but
  #   swaylock blocks access. Cold-boot attack requires specialist hardware
  #   and access within minutes of the device sleeping.
  # - After HibernateDelaySec (30min, configured in power.nix), the system
  #   would hibernate and power off for full protection — but hibernate
  #   requires a swap partition not yet added to disko.nix.
  #
  # Note: boot.initrd.luks.devices.cryptroot is generated by
  # nixos-generate-config after install (it detects the LUKS root).
  # allowDiscards can be added there manually if desired.
}
