{
  # Crypto modules in initrd for LUKS unlock at boot.
  # The boot.initrd.luks.devices.cryptroot entry is generated by
  # nixos-generate-config and lives in hardware-configuration.nix.
  nixos.modules.luks-initrd = {
    boot.initrd.availableKernelModules = [ "aesni_intel" "cryptd" ];
  };
}
