name: nix eval

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  eval:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: DeterminateSystems/nix-installer-action@v14

      - name: eval kuraokami
        run: nix eval .#nixosConfigurations.kuraokami.config.system.build.toplevel.drvPath

      - name: eval nidhoggr
        run: nix eval .#nixosConfigurations.nidhoggr.config.system.build.toplevel.drvPath

      - name: eval homeserver
        run: nix eval .#nixosConfigurations.homeserver.config.system.build.toplevel.drvPath
